apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/requester: argocd
    openshift.io/display-name: vm-gitops
    argocd.argoproj.io/sync-wave: "-1"    
  labels:
    kubernetes.io/metadata.name: vm-gitops
  name: vm-gitops