apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhelvm
  namespace: argocd
spec:
  destination:
    namespace: vm-gitops
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: vms
    repoURL: "https://github.com/gmidha1/virtdemos.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true